/**
 * IANA timezone allowlist with the alphabetic zone abbreviations that may appear
 * in email dates (e.g. "5:30 PM CEST"). Each entry pairs a canonical IANA
 * `tzCode` with every alphabetic abbreviation that names it across the year.
 *
 * Provenance (authored, not runtime): abbreviations are the union of the
 * Wikipedia "List of tz database time zones" SDT/DST columns and luxon's
 * en-US short names sampled in January and July. Numeric-only zones (Wikipedia
 * shows "+12", luxon shows "GMT+N") carry no abbreviation — the offset is
 * derived at runtime, never baked, because it is not static across the year or
 * across tz-database revisions.
 *
 * Pure data constant — no runtime lookups, no external dependencies.
 */
export interface TimeZoneEntry {
  readonly tzCode: string;
  readonly abbreviations: readonly string[];
}

export const TIMEZONE_ENTRIES: readonly TimeZoneEntry[] = [
  { tzCode: "Pacific/Niue", abbreviations: [] },
  { tzCode: "Pacific/Pago_Pago", abbreviations: ["SST"] },
  { tzCode: "Pacific/Honolulu", abbreviations: ["HST"] },
  { tzCode: "Pacific/Rarotonga", abbreviations: [] },
  { tzCode: "Pacific/Tahiti", abbreviations: [] },
  { tzCode: "Pacific/Marquesas", abbreviations: [] },
  { tzCode: "America/Anchorage", abbreviations: ["AKDT","AKST"] },
  { tzCode: "Pacific/Gambier", abbreviations: [] },
  { tzCode: "America/Los_Angeles", abbreviations: ["PDT","PST"] },
  { tzCode: "America/Tijuana", abbreviations: ["PDT","PST"] },
  { tzCode: "America/Vancouver", abbreviations: ["MST","PDT","PST"] },
  { tzCode: "America/Whitehorse", abbreviations: ["MST"] },
  { tzCode: "Pacific/Pitcairn", abbreviations: [] },
  { tzCode: "America/Denver", abbreviations: ["MDT","MST"] },
  { tzCode: "America/Phoenix", abbreviations: ["MST"] },
  { tzCode: "America/Mazatlan", abbreviations: ["MST"] },
  { tzCode: "America/Dawson_Creek", abbreviations: ["MST"] },
  { tzCode: "America/Edmonton", abbreviations: ["CST","MDT","MST"] },
  { tzCode: "America/Hermosillo", abbreviations: ["MST"] },
  { tzCode: "America/Yellowknife", abbreviations: ["CST","MDT","MST"] },
  { tzCode: "America/Belize", abbreviations: ["CST"] },
  { tzCode: "America/Chicago", abbreviations: ["CDT","CST"] },
  { tzCode: "America/Mexico_City", abbreviations: ["CST"] },
  { tzCode: "America/Regina", abbreviations: ["CST"] },
  { tzCode: "America/Tegucigalpa", abbreviations: ["CST"] },
  { tzCode: "America/Winnipeg", abbreviations: ["CDT","CST"] },
  { tzCode: "America/Costa_Rica", abbreviations: ["CST"] },
  { tzCode: "America/El_Salvador", abbreviations: ["CST"] },
  { tzCode: "Pacific/Galapagos", abbreviations: [] },
  { tzCode: "America/Guatemala", abbreviations: ["CST"] },
  { tzCode: "America/Managua", abbreviations: ["CST"] },
  { tzCode: "America/Cancun", abbreviations: ["EST"] },
  { tzCode: "America/Bogota", abbreviations: [] },
  { tzCode: "Pacific/Easter", abbreviations: [] },
  { tzCode: "America/New_York", abbreviations: ["EDT","EST"] },
  { tzCode: "America/Iqaluit", abbreviations: ["EDT","EST"] },
  { tzCode: "America/Toronto", abbreviations: ["EDT","EST"] },
  { tzCode: "America/Guayaquil", abbreviations: [] },
  { tzCode: "America/Havana", abbreviations: ["CDT","CST"] },
  { tzCode: "America/Jamaica", abbreviations: ["EST"] },
  { tzCode: "America/Lima", abbreviations: [] },
  { tzCode: "America/Nassau", abbreviations: ["EDT","EST"] },
  { tzCode: "America/Panama", abbreviations: ["EST"] },
  { tzCode: "America/Port-au-Prince", abbreviations: ["EDT","EST"] },
  { tzCode: "America/Rio_Branco", abbreviations: [] },
  { tzCode: "America/Halifax", abbreviations: ["ADT","AST"] },
  { tzCode: "America/Barbados", abbreviations: ["AST"] },
  { tzCode: "Atlantic/Bermuda", abbreviations: ["ADT","AST"] },
  { tzCode: "America/Boa_Vista", abbreviations: [] },
  { tzCode: "America/Caracas", abbreviations: [] },
  { tzCode: "America/Curacao", abbreviations: ["AST"] },
  { tzCode: "America/Grand_Turk", abbreviations: ["EDT","EST"] },
  { tzCode: "America/Guyana", abbreviations: [] },
  { tzCode: "America/La_Paz", abbreviations: [] },
  { tzCode: "America/Manaus", abbreviations: [] },
  { tzCode: "America/Martinique", abbreviations: ["AST"] },
  { tzCode: "America/Port_of_Spain", abbreviations: ["AST"] },
  { tzCode: "America/Porto_Velho", abbreviations: [] },
  { tzCode: "America/Puerto_Rico", abbreviations: ["AST"] },
  { tzCode: "America/Santo_Domingo", abbreviations: ["AST"] },
  { tzCode: "America/Thule", abbreviations: ["ADT","AST"] },
  { tzCode: "America/St_Johns", abbreviations: ["NDT","NST"] },
  { tzCode: "America/Araguaina", abbreviations: [] },
  { tzCode: "America/Asuncion", abbreviations: [] },
  { tzCode: "America/Belem", abbreviations: [] },
  { tzCode: "America/Argentina/Buenos_Aires", abbreviations: [] },
  { tzCode: "America/Campo_Grande", abbreviations: [] },
  { tzCode: "America/Cayenne", abbreviations: [] },
  { tzCode: "America/Cuiaba", abbreviations: [] },
  { tzCode: "America/Fortaleza", abbreviations: [] },
  { tzCode: "America/Godthab", abbreviations: [] },
  { tzCode: "America/Maceio", abbreviations: [] },
  { tzCode: "America/Miquelon", abbreviations: [] },
  { tzCode: "America/Montevideo", abbreviations: [] },
  { tzCode: "Antarctica/Palmer", abbreviations: [] },
  { tzCode: "America/Paramaribo", abbreviations: [] },
  { tzCode: "America/Punta_Arenas", abbreviations: [] },
  { tzCode: "America/Recife", abbreviations: [] },
  { tzCode: "Antarctica/Rothera", abbreviations: [] },
  { tzCode: "America/Bahia", abbreviations: [] },
  { tzCode: "America/Santiago", abbreviations: [] },
  { tzCode: "Atlantic/Stanley", abbreviations: [] },
  { tzCode: "America/Noronha", abbreviations: [] },
  { tzCode: "America/Sao_Paulo", abbreviations: [] },
  { tzCode: "Atlantic/South_Georgia", abbreviations: [] },
  { tzCode: "Atlantic/Azores", abbreviations: [] },
  { tzCode: "Atlantic/Cape_Verde", abbreviations: [] },
  { tzCode: "America/Scoresbysund", abbreviations: [] },
  { tzCode: "Africa/Abidjan", abbreviations: ["GMT"] },
  { tzCode: "Africa/Accra", abbreviations: ["GMT"] },
  { tzCode: "Africa/Bissau", abbreviations: ["GMT"] },
  { tzCode: "Atlantic/Canary", abbreviations: ["WEST","WET"] },
  { tzCode: "Africa/Casablanca", abbreviations: [] },
  { tzCode: "America/Danmarkshavn", abbreviations: ["GMT"] },
  { tzCode: "Europe/Dublin", abbreviations: ["GMT","IST"] },
  { tzCode: "Africa/El_Aaiun", abbreviations: [] },
  { tzCode: "Atlantic/Faroe", abbreviations: ["WEST","WET"] },
  { tzCode: "Etc/GMT", abbreviations: ["UTC"] },
  { tzCode: "Europe/Lisbon", abbreviations: ["WEST","WET"] },
  { tzCode: "Europe/London", abbreviations: ["BST","GMT"] },
  { tzCode: "Africa/Monrovia", abbreviations: ["GMT"] },
  { tzCode: "Atlantic/Reykjavik", abbreviations: ["GMT"] },
  { tzCode: "Africa/Algiers", abbreviations: ["CET"] },
  { tzCode: "Europe/Amsterdam", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Andorra", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Berlin", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Brussels", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Budapest", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Belgrade", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Prague", abbreviations: ["CEST","CET"] },
  { tzCode: "Africa/Ceuta", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Copenhagen", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Gibraltar", abbreviations: ["CEST","CET"] },
  { tzCode: "Africa/Lagos", abbreviations: ["WAT"] },
  { tzCode: "Europe/Luxembourg", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Madrid", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Malta", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Monaco", abbreviations: ["CEST","CET"] },
  { tzCode: "Africa/Ndjamena", abbreviations: ["WAT"] },
  { tzCode: "Europe/Oslo", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Paris", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Rome", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Stockholm", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Tirane", abbreviations: ["CEST","CET"] },
  { tzCode: "Africa/Tunis", abbreviations: ["CET"] },
  { tzCode: "Europe/Vienna", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Warsaw", abbreviations: ["CEST","CET"] },
  { tzCode: "Europe/Zurich", abbreviations: ["CEST","CET"] },
  { tzCode: "Asia/Amman", abbreviations: [] },
  { tzCode: "Europe/Athens", abbreviations: ["EEST","EET"] },
  { tzCode: "Asia/Beirut", abbreviations: ["EEST","EET"] },
  { tzCode: "Europe/Bucharest", abbreviations: ["EEST","EET"] },
  { tzCode: "Africa/Cairo", abbreviations: ["EEST","EET"] },
  { tzCode: "Europe/Chisinau", abbreviations: ["EEST","EET"] },
  { tzCode: "Asia/Damascus", abbreviations: [] },
  { tzCode: "Asia/Gaza", abbreviations: ["EEST","EET"] },
  { tzCode: "Europe/Helsinki", abbreviations: ["EEST","EET"] },
  { tzCode: "Asia/Jerusalem", abbreviations: ["IDT","IST"] },
  { tzCode: "Africa/Johannesburg", abbreviations: ["SAST"] },
  { tzCode: "Africa/Khartoum", abbreviations: ["CAT"] },
  { tzCode: "Europe/Kiev", abbreviations: ["EEST","EET"] },
  { tzCode: "Africa/Maputo", abbreviations: ["CAT"] },
  { tzCode: "Europe/Kaliningrad", abbreviations: ["EET"] },
  { tzCode: "Asia/Nicosia", abbreviations: ["EEST","EET"] },
  { tzCode: "Europe/Riga", abbreviations: ["EEST","EET"] },
  { tzCode: "Europe/Sofia", abbreviations: ["EEST","EET"] },
  { tzCode: "Europe/Tallinn", abbreviations: ["EEST","EET"] },
  { tzCode: "Africa/Tripoli", abbreviations: ["EET"] },
  { tzCode: "Europe/Vilnius", abbreviations: ["EEST","EET"] },
  { tzCode: "Africa/Windhoek", abbreviations: ["CAT"] },
  { tzCode: "Asia/Baghdad", abbreviations: [] },
  { tzCode: "Europe/Istanbul", abbreviations: [] },
  { tzCode: "Europe/Minsk", abbreviations: [] },
  { tzCode: "Europe/Moscow", abbreviations: ["MSK"] },
  { tzCode: "Africa/Nairobi", abbreviations: ["EAT"] },
  { tzCode: "Asia/Qatar", abbreviations: [] },
  { tzCode: "Asia/Riyadh", abbreviations: [] },
  { tzCode: "Antarctica/Syowa", abbreviations: [] },
  { tzCode: "Asia/Tehran", abbreviations: [] },
  { tzCode: "Asia/Baku", abbreviations: [] },
  { tzCode: "Asia/Dubai", abbreviations: [] },
  { tzCode: "Indian/Mahe", abbreviations: [] },
  { tzCode: "Indian/Mauritius", abbreviations: [] },
  { tzCode: "Europe/Samara", abbreviations: [] },
  { tzCode: "Indian/Reunion", abbreviations: [] },
  { tzCode: "Asia/Tbilisi", abbreviations: [] },
  { tzCode: "Asia/Yerevan", abbreviations: [] },
  { tzCode: "Asia/Kabul", abbreviations: [] },
  { tzCode: "Asia/Aqtau", abbreviations: [] },
  { tzCode: "Asia/Aqtobe", abbreviations: [] },
  { tzCode: "Asia/Ashgabat", abbreviations: [] },
  { tzCode: "Asia/Dushanbe", abbreviations: [] },
  { tzCode: "Asia/Karachi", abbreviations: ["PKT"] },
  { tzCode: "Indian/Kerguelen", abbreviations: [] },
  { tzCode: "Indian/Maldives", abbreviations: [] },
  { tzCode: "Antarctica/Mawson", abbreviations: [] },
  { tzCode: "Asia/Yekaterinburg", abbreviations: [] },
  { tzCode: "Asia/Tashkent", abbreviations: [] },
  { tzCode: "Asia/Colombo", abbreviations: [] },
  { tzCode: "Asia/Kolkata", abbreviations: ["IST"] },
  { tzCode: "Asia/Kathmandu", abbreviations: [] },
  { tzCode: "Asia/Almaty", abbreviations: [] },
  { tzCode: "Asia/Bishkek", abbreviations: [] },
  { tzCode: "Indian/Chagos", abbreviations: [] },
  { tzCode: "Asia/Dhaka", abbreviations: [] },
  { tzCode: "Asia/Omsk", abbreviations: [] },
  { tzCode: "Asia/Thimphu", abbreviations: [] },
  { tzCode: "Antarctica/Vostok", abbreviations: [] },
  { tzCode: "Indian/Cocos", abbreviations: [] },
  { tzCode: "Asia/Yangon", abbreviations: [] },
  { tzCode: "Asia/Bangkok", abbreviations: [] },
  { tzCode: "Indian/Christmas", abbreviations: [] },
  { tzCode: "Antarctica/Davis", abbreviations: [] },
  { tzCode: "Asia/Saigon", abbreviations: [] },
  { tzCode: "Asia/Hovd", abbreviations: [] },
  { tzCode: "Asia/Jakarta", abbreviations: ["WIB"] },
  { tzCode: "Asia/Krasnoyarsk", abbreviations: [] },
  { tzCode: "Asia/Brunei", abbreviations: [] },
  { tzCode: "Asia/Shanghai", abbreviations: ["CST"] },
  { tzCode: "Asia/Choibalsan", abbreviations: [] },
  { tzCode: "Asia/Hong_Kong", abbreviations: ["HKT"] },
  { tzCode: "Asia/Kuala_Lumpur", abbreviations: [] },
  { tzCode: "Asia/Macau", abbreviations: ["CST"] },
  { tzCode: "Asia/Makassar", abbreviations: ["WITA"] },
  { tzCode: "Asia/Manila", abbreviations: ["PST"] },
  { tzCode: "Asia/Irkutsk", abbreviations: [] },
  { tzCode: "Asia/Singapore", abbreviations: [] },
  { tzCode: "Asia/Taipei", abbreviations: ["CST"] },
  { tzCode: "Asia/Ulaanbaatar", abbreviations: [] },
  { tzCode: "Australia/Perth", abbreviations: ["AWST"] },
  { tzCode: "Asia/Pyongyang", abbreviations: ["KST"] },
  { tzCode: "Asia/Dili", abbreviations: [] },
  { tzCode: "Asia/Jayapura", abbreviations: ["WIT"] },
  { tzCode: "Asia/Yakutsk", abbreviations: [] },
  { tzCode: "Pacific/Palau", abbreviations: [] },
  { tzCode: "Asia/Seoul", abbreviations: ["KST"] },
  { tzCode: "Asia/Tokyo", abbreviations: ["JST"] },
  { tzCode: "Australia/Darwin", abbreviations: ["ACST"] },
  { tzCode: "Antarctica/DumontDUrville", abbreviations: [] },
  { tzCode: "Australia/Brisbane", abbreviations: ["AEST"] },
  { tzCode: "Pacific/Guam", abbreviations: ["ChST"] },
  { tzCode: "Asia/Vladivostok", abbreviations: [] },
  { tzCode: "Pacific/Port_Moresby", abbreviations: [] },
  { tzCode: "Pacific/Chuuk", abbreviations: [] },
  { tzCode: "Australia/Adelaide", abbreviations: ["ACDT","ACST"] },
  { tzCode: "Antarctica/Casey", abbreviations: [] },
  { tzCode: "Australia/Hobart", abbreviations: ["AEDT","AEST"] },
  { tzCode: "Australia/Sydney", abbreviations: ["AEDT","AEST"] },
  { tzCode: "Pacific/Efate", abbreviations: [] },
  { tzCode: "Pacific/Guadalcanal", abbreviations: [] },
  { tzCode: "Pacific/Kosrae", abbreviations: [] },
  { tzCode: "Asia/Magadan", abbreviations: [] },
  { tzCode: "Pacific/Norfolk", abbreviations: [] },
  { tzCode: "Pacific/Noumea", abbreviations: [] },
  { tzCode: "Pacific/Pohnpei", abbreviations: [] },
  { tzCode: "Pacific/Funafuti", abbreviations: [] },
  { tzCode: "Pacific/Kwajalein", abbreviations: [] },
  { tzCode: "Pacific/Majuro", abbreviations: [] },
  { tzCode: "Asia/Kamchatka", abbreviations: [] },
  { tzCode: "Pacific/Nauru", abbreviations: [] },
  { tzCode: "Pacific/Tarawa", abbreviations: [] },
  { tzCode: "Pacific/Wake", abbreviations: [] },
  { tzCode: "Pacific/Wallis", abbreviations: [] },
  { tzCode: "Pacific/Auckland", abbreviations: ["NZDT","NZST"] },
  { tzCode: "Pacific/Enderbury", abbreviations: [] },
  { tzCode: "Pacific/Fakaofo", abbreviations: [] },
  { tzCode: "Pacific/Fiji", abbreviations: [] },
  { tzCode: "Pacific/Tongatapu", abbreviations: [] },
  { tzCode: "Pacific/Apia", abbreviations: [] },
  { tzCode: "Pacific/Kiritimati", abbreviations: [] },
];

let allowlistCache: ReadonlySet<string> | undefined;
/** Set of valid IANA tzCodes for API validation — memoized on first access. */
export function timezoneAllowlist(): ReadonlySet<string> {
  return (allowlistCache ??= new Set(TIMEZONE_ENTRIES.map((e) => e.tzCode)));
}

export const DEFAULT_TIMEZONE = "Europe/London";
